package main

var (
	prerolleddates = map[string]int{}
	aetates        = map[string]int{
		"Ant":                 150,
		"August fere":         1,
		"Ant/Aur":             160,
		"Ant. Pius":           150,
		"Antoninus Pius":      150,
		"Antonine":            150,
		"Ant. Pius & M. Aur.": 160,
		"Aur":                 170,
		"Aur/Carac":           200,
		"Aur/Commod":          160,
		"Carac":               205,
		"Chr":                 400,
		"Claud":               50,
		"Claudius":            50,
		"Aug/Claud":           30,
		"Aug/Tib":             10,
		"Claud/Nero":          55,
		"Commod":              185,
		"Dioc":                290,
		"Dom":                 90,
		"Flav":                85,
		"Had":                 125,
		"Hadriani":            125,
		"Had/Aur":             150,
		"Had/Ant":             155,
		"Hell tard":           -1,
		"Hell":                -250,
		"Imp tard":            400,
		"imp":                 200,
		"Imp":                 200,
		"inferior":            1200,
		"Nero":                60,
		"Nerv":                97,
		"Nerv/Tra":            100,
		"TráHad":              115,
		"Rom tard":            250,
		"Rom":                 50,
		"tard":                1000,
		"Tib":                 25,
		"Tib/Gaii":            35,
		"Gaii":                40,
		"Calig":               40,
		"Tit":                 80,
		"Tra":                 105,
		"Tra/Had":             115,
		"Ves":                 70,
		"Ves/Dom":             80,
		"Augusti":             1,
		"Lycurgi":             -350,
		"Macedon":             -275,
		"Aug":                 1,
		"Rom/Byz":             550,
		"Byz":                 700,
		"Byzant":              700,
		"Byzantina":           700,
		"Just":                550,
		"Hell.":               -250,
		"Hellen":              -250,
		"Hellenistic":         -250,
		"Hellenist":           -250,
		"Severianae":          210,
		"fin Tib":             35,
		"fin Aug":             10,
		"fin Claud":           50,
		"fin Dom":             95,
		"fin Hell":            -1,
		"fin Nero":            65,
		"fin Rom":             325,
		"fin Tra":             115,
		"incert":              9999,
		"init Ant":            155,
		"init Aug":            -15,
		"init Byz":            450,
		"init Chr":            350,
		"init Had":            120,
		"init Hell":           -250,
		"init Rom":            -50,
		"init imp":            50,
		"init imper":          50,
		"med Hell":            -150,
	}
	romannumerals = map[string]int{
		"I":    1,
		"II":   2,
		"III":  3,
		"IV":   4,
		"V":    5,
		"VI":   6,
		"VII":  7,
		"VIII": 8,
		"IX":   9,
		"X":    10,
		"XI":   11,
		"XII":  12,
		"XIII": 13,
		"XIV":  14,
		"XV":   15,
	}
)
